/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    'shop-items': ShopItem;
    'trade-proposals': TradeProposal;
    'proposal-versions': ProposalVersion;
    'proposal-messages': ProposalMessage;
    notifications: Notification;
    reports: Report;
    disputes: Dispute;
    'view-history': ViewHistory;
    'item-views': ItemView;
    'search-history': SearchHistory;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'shop-items': ShopItemsSelect<false> | ShopItemsSelect<true>;
    'trade-proposals': TradeProposalsSelect<false> | TradeProposalsSelect<true>;
    'proposal-versions': ProposalVersionsSelect<false> | ProposalVersionsSelect<true>;
    'proposal-messages': ProposalMessagesSelect<false> | ProposalMessagesSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    reports: ReportsSelect<false> | ReportsSelect<true>;
    disputes: DisputesSelect<false> | DisputesSelect<true>;
    'view-history': ViewHistorySelect<false> | ViewHistorySelect<true>;
    'item-views': ItemViewsSelect<false> | ItemViewsSelect<true>;
    'search-history': SearchHistorySelect<false> | SearchHistorySelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'match-score-config': MatchScoreConfig;
  };
  globalsSelect: {
    'match-score-config': MatchScoreConfigSelect<false> | MatchScoreConfigSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  naam?: string | null;
  avatar?: (number | null) | Media;
  /**
   * Wijk-/postcode-niveau, standaard zichtbaar voor anderen (bv. "1017 CJ" of "Amsterdam-Zuid").
   */
  locatie_ruw?: string | null;
  /**
   * Precieze coördinaten. Pas delen na een bevestigde afspraak (fysieke veiligheid). Dit veld regelt alleen opslag, niet wanneer het getoond wordt.
   *
   * @minItems 2
   * @maxItems 2
   */
  locatie_exact?: [number, number] | null;
  /**
   * Beide verificatievelden moeten true zijn voordat een gebruiker een TradeProposal mag starten of accepteren (afgedwongen in TradeProposals, niet hier).
   */
  geverifieerd_email?: boolean | null;
  geverifieerd_telefoon?: boolean | null;
  /**
   * Intern, geen gebruikersinput. Voor sockpuppet-/collusiedetectie.
   */
  signup_device_ip?: string | null;
  /**
   * Denormalized teller. Wordt automatisch +1 gezet voor beide deelnemers zodra een TradeProposal op "Voltooid" komt (zie hooks in TradeProposals.ts).
   */
  voltooide_ruilen?: number | null;
  /**
   * Denormalized teller. +1 voor beide deelnemers bij "Verlopen"; +1 alleen voor wie intrekt bij "Ingetrokken"; GEEN wijziging bij "Geweigerd" (zie hooks in TradeProposals.ts).
   */
  ingetrokken_of_geweigerd?: number | null;
  laatst_actief?: string | null;
  /**
   * Simpele aan/uit-schakelaar, geen niveau-instelling.
   */
  ai_onderhandelhulp_aan?: boolean | null;
  /**
   * Aan/uit-beheer voor gebruik van ViewHistory/SearchHistory in suggesties/matching.
   */
  geschiedenis_gebruik_aan?: boolean | null;
  /**
   * Breed, statisch signaal, vervangt het vervallen WishlistItems. Kan op elke diepte in de categorieboom staan.
   */
  interesses?: (number | Category)[] | null;
  /**
   * Wordt true zodra de verplichte intake (interesses + locatie) na registratie is doorlopen. Zolang false: gebruiker naar intake-flow i.p.v. Ontdekken.
   */
  onboarding_voltooid?: boolean | null;
  /**
   * Bij accountverwijdering: Geanonimiseerd i.p.v. hard delete. Zodra dit veld naar Geanonimiseerd gaat, scrubt een hook automatisch naam/email/avatar/locatie_exact. Gekoppelde ShopItems/TradeProposals/ProposalMessages blijven bestaan.
   */
  account_status?: ('actief' | 'geanonimiseerd') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Vaste, hiërarchische categorieën/tags. Elke knoop is een geldig eindpunt (bv. "Auto's" is net zo geldig als "Auto's > BMW > 3-serie").
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  naam: string;
  /**
   * Optioneel. Leeg = hoofdcategorie.
   */
  parent?: (number | null) | Category;
  /**
   * URL-vriendelijke, unieke sleutel.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-items".
 */
export interface ShopItem {
  id: number;
  eigenaar: number | User;
  titel: string;
  beschrijving: string;
  /**
   * Voedt de matchscore-factor "aanbod-vraag overlap" tegen Users.interesses van anderen.
   */
  categorie: number | Category;
  fotos: (number | Media)[];
  staat: 'nieuwstaat' | 'zo_goed_als_nieuw' | 'gebruikssporen' | 'duidelijke_gebruikssporen';
  /**
   * Nooit een prijs, vaste schaal, geen prijsrange of vrije tekst.
   */
  waarde_indicatie: 'laag' | 'midden' | 'hoog';
  /**
   * "Beide mogelijk" = beide opties selecteren. Voedt locatie-weging in de matchscore.
   */
  overdracht: ('ophalen' | 'verzenden')[];
  /**
   * Een item blijft open voor meerdere gelijktijdige voorstellen; dit veld is de ruil-levenscyclus van een al gepubliceerd item (geen concept/draft-staat, die volgt later apart).
   */
  status: 'beschikbaar' | 'in_onderhandeling' | 'geruild' | 'ingetrokken';
  /**
   * Wat de aanbieder voor dit item het liefst terugkrijgt. Leeg = alles mag geboden worden; productmatch valt dan terug op categorie/Interesses-overlap. Bewust geen apart boolean-veld.
   */
  gewenst_terug?: (number | null) | Category;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trade-proposals".
 */
export interface TradeProposal {
  id: number;
  /**
   * Het item waarvan de productpagina dit ruilvoorstel startte. Elk voorstel draait om precies 1 anker-item (zo toont ook het ruilvoorstel-paneel altijd 1 titel/foto in de header), ongeacht hoeveel items er in latere versies bij komen. deelnemer_a is altijd de eigenaar van dit item ("aanbieder"), deelnemer_b altijd wie het voorstel startte ("zoeker").
   */
  context_item: number | ShopItem;
  /**
   * Eigenaar van context_item ("aanbieder"), zie context_item hierboven.
   */
  deelnemer_a: number | User;
  /**
   * Wie het voorstel startte ("zoeker"), zie context_item hierboven.
   */
  deelnemer_b: number | User;
  /**
   * Wie als eerste op "Akkoord geven" klikte (status geaccepteerd_wacht_op_bevestiging). De ANDERE deelnemer moet dit vervolgens zelf bevestigen voordat status voltooid wordt. Leeg zolang niemand akkoord heeft gegeven; wordt weer leeggemaakt bij weigeren/sluiten.
   */
  akkoord_door?: (number | null) | User;
  /**
   * Elke statuswijziging triggert een Notification (categorie Ruilvoorstel) en, bij voltooid/verlopen/ingetrokken, een trackrecord-teller op Users (zie hooks in dit bestand).
   */
  status:
    | 'voorgesteld'
    | 'in_onderhandeling'
    | 'geaccepteerd_wacht_op_bevestiging'
    | 'bevestigd_door_a'
    | 'bevestigd_door_b'
    | 'voltooid'
    | 'geweigerd'
    | 'ingetrokken'
    | 'verlopen';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proposal-versions".
 */
export interface ProposalVersion {
  id: number;
  voorstel: number | TradeProposal;
  /**
   * Wie deze versie voorstelde.
   */
  auteur: number | User;
  items_van_a?: (number | ShopItem)[] | null;
  items_van_b?: (number | ShopItem)[] | null;
  /**
   * Wat de lichte AI-onderhandelhulp bij deze versie voorstelde, indien getoond.
   */
  ai_balans_suggestie?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proposal-messages".
 */
export interface ProposalMessage {
  id: number;
  voorstel: number | TradeProposal;
  auteur: number | User;
  tekst: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Bewust een beperkte set triggers, geen regel per systeemgebeurtenis. Matches triggeren hier expliciet NIET, dat loopt via een visuele indicator op het productkaartje (mag-later, geen v1-veld).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  ontvanger: number | User;
  /**
   * Bepaalt de kleurcodering in de UI: groen / goud / grijs-gemuted.
   */
  categorie: 'ruilvoorstel' | 'geschil' | 'systeem';
  /**
   * Ingevuld bij categorie Ruilvoorstel.
   */
  gerelateerd_voorstel?: (number | null) | TradeProposal;
  /**
   * Ingevuld bij categorie Geschil.
   */
  gerelateerd_geschil?: (number | null) | Dispute;
  tekst: string;
  gelezen?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Geschil = eerlijk meningsverschil over wat er gebeurd is. Hybride proces (besloten): eerst partijen zelf, bij impasse beslist het platform-team bindend (eBay Resolution Center-model). Exacte termijnen/bewijsvorm/appel nog niet uitgewerkt.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "disputes".
 */
export interface Dispute {
  id: number;
  voorstel: number | TradeProposal;
  indiener: number | User;
  omschrijving: string;
  /**
   * Bij status Beslist: triggert een Notification (categorie Geschil) naar beide deelnemers.
   */
  status: 'open' | 'in_onderling_overleg' | 'geescaleerd_naar_team' | 'beslist' | 'gesloten';
  /**
   * Optioneel: Swopla-teamlid dat de knoop doorhakt bij escalatie.
   */
  beoordeeld_door?: (number | null) | User;
  /**
   * Optioneel: toelichting op de bindende beslissing.
   */
  beslissing?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Melden = kwade trouw/misbruik. Bewust gescheiden van Disputes (geschil = eerlijk meningsverschil). Nooit samenvoegen.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports".
 */
export interface Report {
  id: number;
  melder: number | User;
  /**
   * Waarover wordt gemeld: een gebruiker of een specifiek item.
   */
  onderwerp:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'shop-items';
        value: number | ShopItem;
      };
  reden: string;
  /**
   * Statusopties nog niet expliciet besloten in het concept, eerste redelijke aanname, ter review.
   */
  status: 'open' | 'in_behandeling' | 'afgehandeld';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "view-history".
 */
export interface ViewHistory {
  id: number;
  kijker: number | User;
  bekeken_profiel: number | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Log van weergaven per shop-item, voor "X keer bekeken" en de Inzichten-zijbalk (weergaven + trend) op het Shop-scherm.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "item-views".
 */
export interface ItemView {
  id: number;
  item: number | ShopItem;
  /**
   * Automatisch gezet vanaf item.eigenaar, niet handmatig invullen.
   */
  eigenaar?: (number | null) | User;
  /**
   * Optioneel: er is nog geen echte auth, dus niet elke weergave heeft een bekende kijker.
   */
  kijker?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Dit is ook de plek waar specifiek, actueel zoeken landt, vervangt het vervallen WishlistItems (zie Categories/Users.interesses voor het brede, statische signaal).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search-history".
 */
export interface SearchHistory {
  id: number;
  gebruiker: number | User;
  zoekterm: string;
  filters?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'shop-items';
        value: number | ShopItem;
      } | null)
    | ({
        relationTo: 'trade-proposals';
        value: number | TradeProposal;
      } | null)
    | ({
        relationTo: 'proposal-versions';
        value: number | ProposalVersion;
      } | null)
    | ({
        relationTo: 'proposal-messages';
        value: number | ProposalMessage;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'reports';
        value: number | Report;
      } | null)
    | ({
        relationTo: 'disputes';
        value: number | Dispute;
      } | null)
    | ({
        relationTo: 'view-history';
        value: number | ViewHistory;
      } | null)
    | ({
        relationTo: 'item-views';
        value: number | ItemView;
      } | null)
    | ({
        relationTo: 'search-history';
        value: number | SearchHistory;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  naam?: T;
  avatar?: T;
  locatie_ruw?: T;
  locatie_exact?: T;
  geverifieerd_email?: T;
  geverifieerd_telefoon?: T;
  signup_device_ip?: T;
  voltooide_ruilen?: T;
  ingetrokken_of_geweigerd?: T;
  laatst_actief?: T;
  ai_onderhandelhulp_aan?: T;
  geschiedenis_gebruik_aan?: T;
  interesses?: T;
  onboarding_voltooid?: T;
  account_status?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  naam?: T;
  parent?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-items_select".
 */
export interface ShopItemsSelect<T extends boolean = true> {
  eigenaar?: T;
  titel?: T;
  beschrijving?: T;
  categorie?: T;
  fotos?: T;
  staat?: T;
  waarde_indicatie?: T;
  overdracht?: T;
  status?: T;
  gewenst_terug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trade-proposals_select".
 */
export interface TradeProposalsSelect<T extends boolean = true> {
  context_item?: T;
  deelnemer_a?: T;
  deelnemer_b?: T;
  akkoord_door?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proposal-versions_select".
 */
export interface ProposalVersionsSelect<T extends boolean = true> {
  voorstel?: T;
  auteur?: T;
  items_van_a?: T;
  items_van_b?: T;
  ai_balans_suggestie?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proposal-messages_select".
 */
export interface ProposalMessagesSelect<T extends boolean = true> {
  voorstel?: T;
  auteur?: T;
  tekst?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  ontvanger?: T;
  categorie?: T;
  gerelateerd_voorstel?: T;
  gerelateerd_geschil?: T;
  tekst?: T;
  gelezen?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports_select".
 */
export interface ReportsSelect<T extends boolean = true> {
  melder?: T;
  onderwerp?: T;
  reden?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "disputes_select".
 */
export interface DisputesSelect<T extends boolean = true> {
  voorstel?: T;
  indiener?: T;
  omschrijving?: T;
  status?: T;
  beoordeeld_door?: T;
  beslissing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "view-history_select".
 */
export interface ViewHistorySelect<T extends boolean = true> {
  kijker?: T;
  bekeken_profiel?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "item-views_select".
 */
export interface ItemViewsSelect<T extends boolean = true> {
  item?: T;
  eigenaar?: T;
  kijker?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search-history_select".
 */
export interface SearchHistorySelect<T extends boolean = true> {
  gebruiker?: T;
  zoekterm?: T;
  filters?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Matchscore-gewichten. Exacte getallen nog niet besloten, richting/volgorde staat vast, huidige waardes zijn placeholders.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "match-score-config".
 */
export interface MatchScoreConfig {
  id: number;
  /**
   * Weging van overlap tussen ShopItems.gewenst_terug en het aanbod van de bezoeker, wanneer dat veld is ingevuld.
   */
  gewicht_productmatch_specifiek?: number | null;
  /**
   * Weging van de gewone aanbod-vraag/Interesses-overlap, gebruikt wanneer gewenst_terug leeg is. Lager dan het specifieke gewicht.
   */
  gewicht_productmatch_algemeen?: number | null;
  gewicht_staat_en_waarde?: number | null;
  /**
   * Shop-brede overlap.
   */
  gewicht_aanbod_vraag_overlap?: number | null;
  gewicht_locatie?: number | null;
  gewicht_betrouwbaarheid?: number | null;
  gewicht_sociaal?: number | null;
  /**
   * Optioneel, mag later, vandaar default 0.
   */
  gewicht_reviews?: number | null;
  locatie_weging_ophalen_vs_verzenden?: number | null;
  /**
   * Weegt het zwaarst, actiefste signaal.
   */
  gewicht_ontdekken_gewenst_terug?: number | null;
  gewicht_ontdekken_zoekgeschiedenis?: number | null;
  /**
   * Breedste, meest passieve signaal, ook de terugval wanneer de twee bovenstaande ontbreken.
   */
  gewicht_ontdekken_interesses?: number | null;
  /**
   * Percentage vanaf waar een item gegarandeerd op de eerste pagina/regels staat (besloten: 75). Volgorde binnen deze band mag door elkaar lopen.
   */
  ontdekken_hoge_match_drempel?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "match-score-config_select".
 */
export interface MatchScoreConfigSelect<T extends boolean = true> {
  gewicht_productmatch_specifiek?: T;
  gewicht_productmatch_algemeen?: T;
  gewicht_staat_en_waarde?: T;
  gewicht_aanbod_vraag_overlap?: T;
  gewicht_locatie?: T;
  gewicht_betrouwbaarheid?: T;
  gewicht_sociaal?: T;
  gewicht_reviews?: T;
  locatie_weging_ophalen_vs_verzenden?: T;
  gewicht_ontdekken_gewenst_terug?: T;
  gewicht_ontdekken_zoekgeschiedenis?: T;
  gewicht_ontdekken_interesses?: T;
  ontdekken_hoge_match_drempel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}